export enum Keyword {
	SELECT = "SELECT",
	INSERT = "INSERT",
	UPDATE = "UPDATE",
	DELETE = "DELETE",
	DISTINCT = "DISTINCT",
	FROM = "FROM",
	WHERE = "WHERE",
	GROUP_BY = "GROUP BY",
	HAVING = "HAVING",
	ORDER_BY = "ORDER BY",
	LIMIT = "LIMIT",
	IDENTIFIER = "IDENTIFIER",
}